#keyvalue: attribute

#map:
#  keyvalue1: something
#  keyvalue2: alsosomething
#  nestedmap:
#    keyvalue3: something

#list:
#  - item1
#  - item2

version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports: 
      - 443:443
    build: requirements/nginx
#    volumes:
#      - ./html:/srcs/requirements/nginx

  mariadb:
    image: mariadb:latest
    ports: 
      - 3306:3306
    env_file:
      - ./.env
#    volumes:
#      - ./html:/srcs/requirements/mariandb

  wordpress:
    image: wordpress:latest
    ports: 
      - 9000:9000
#    volumes:
#      - ./html:/srcs/requirements/wordpress