version: '3.7'

networks:
  disciples:
    name: disciples
    driver: bridge

volumes:
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/kmeixner/data/mariadb_vol

services:
  nginx:
    container_name: matthew
    ports:
      - 443:443
    build: requirements/nginx
    networks:
      - disciples
    restart: on-failure
  #  volumes:
  #    - ./html:/srcs/requirements/nginx

  mariadb:
    container_name: john
    build: requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - disciples
    restart: on-failure

