-- USE mysql;

CREATE USER IF NOT EXISTS 'MDB_USER'@'%' IDENTIFIED BY 'MDB_PWD'; 
CREATE DATABASE IF NOT EXISTS 'MDB_NAME';
GRANT ALL PRIVILEGES ON MDB_NAME.* TO 'MDB_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
-- FLUSH PRIVILEGES;