-- USE mysql;

CREATE USER IF NOT EXISTS 'WORDPRESS_DB_USER'@'%' IDENTIFIED BY 'WORDPRESS_DB_PWD'; 
CREATE DATABASE IF NOT EXISTS WORDPRESS_DB_NAME;
GRANT ALL PRIVILEGES ON WORDPRESS_DB_NAME.* TO 'WORDPRESS_DB_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
-- FLUSH PRIVILEGES;